import { NextResponse } from "next/server";
import { createSupabaseServerClient, createSupabaseAdminClient } from "@/lib/supabase-server";
import { logError } from "@/lib/log-error";

// POST /api/admin/portal-invite
// Body: { email, company_id, expires_hours?, max_uses? }
// Returns: { invite_url, expires_at, max_uses }
export async function POST(request: Request) {
  const origin = process.env.NEXT_PUBLIC_APP_URL ?? new URL(request.url).origin.replace("http://", "https://");

  // Verify caller is an admin
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthenticated" }, { status: 401 });

  const adminClient = createSupabaseAdminClient();
  const { data: profile } = await adminClient
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();

  if (profile?.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  // Parse body
  let body: { email?: string; company_id?: string; expires_hours?: number; max_uses?: number };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { email, company_id, expires_hours = 48, max_uses = 5 } = body;

  if (!email) return NextResponse.json({ error: "email is required" }, { status: 400 });

  const expiresAt = new Date(Date.now() + expires_hours * 60 * 60 * 1000).toISOString();

  // Create invite row (token auto-generated by DB default)
  const { data: invite, error: insertError } = await adminClient
    .from("portal_invites")
    .insert({
      email,
      company_id: company_id ?? null,
      expires_at: expiresAt,
      max_uses,
      created_by: user.id,
    })
    .select("token")
    .single();

  if (insertError || !invite) {
    await logError({
      error: insertError ?? new Error("No invite returned"),
      source: "api/admin/portal-invite",
      action: "insert_invite",
      userId: user.id,
      metadata: { email, company_id },
    });
    return NextResponse.json({ error: "Failed to create invite" }, { status: 500 });
  }

  const inviteUrl = `${origin}/portal/join/${invite.token}`;

  // Optionally send via Resend if RESEND_API_KEY is set
  if (process.env.RESEND_API_KEY) {
    try {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: "LexSutra <hello@send.lexsutra.com>",
          to:   [email],
          subject: "Your LexSutra portal access link",
          html: `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/></head>
<body style="margin:0;padding:0;background:#060a14;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
<div style="max-width:540px;margin:0 auto;padding:40px 24px;">

  <!-- Logo -->
  <div style="text-align:center;margin-bottom:36px;">
    <div style="font-size:22px;font-weight:700;letter-spacing:0.01em;">
      <span style="color:#c9a84c;">Lex</span><span style="color:#e8f4ff;">Sutra</span>
    </div>
    <div style="color:#3d4f60;font-size:10px;letter-spacing:0.1em;text-transform:uppercase;margin-top:4px;">
      EU AI Act · Compliance Diagnostic
    </div>
  </div>

  <!-- Main -->
  <div style="background:#0d1520;border:1px solid rgba(45,156,219,0.15);border-radius:12px;padding:32px;">
    <p style="color:#e8f4ff;font-size:15px;font-weight:600;margin:0 0 8px;">Your compliance portal is ready</p>
    <p style="color:#8899aa;font-size:13px;line-height:1.7;margin:0 0 28px;">
      You have been granted access to your LexSutra EU AI Act compliance portal.
      Use the button below to log in and view your diagnostic status, documents, and reports.
    </p>
    <div style="text-align:center;">
      <a href="${inviteUrl}"
         style="display:inline-block;background:#c9a84c;color:#060a14;padding:13px 32px;
                border-radius:7px;text-decoration:none;font-weight:700;font-size:14px;">
        Access Your Portal →
      </a>
    </div>
    <p style="color:#3d4f60;font-size:11px;text-align:center;margin:20px 0 0;line-height:1.6;">
      This link expires in ${expires_hours} hours · If you did not expect this email, please ignore it.
    </p>
  </div>

  <!-- Footer -->
  <div style="text-align:center;margin-top:28px;">
    <p style="color:#3d4f60;font-size:11px;margin:0;line-height:1.6;">
      LexSutra · lexsutra.com · EU AI Act Compliance Diagnostic<br/>
      LexSutra provides compliance infrastructure tools, not legal advice.
    </p>
  </div>

</div>
</body>
</html>`,
        }),
      });
    } catch (emailErr) {
      // Non-fatal — log but still return the invite URL
      await logError({
        error: emailErr,
        source: "api/admin/portal-invite",
        action: "send_email",
        userId: user.id,
        metadata: { email },
      });
    }
  }

  // Log to activity
  await adminClient.from("activity_log").insert({
    actor_id:    user.id,
    action:      "generate_portal_invite",
    entity_type: "companies",
    entity_id:   company_id ?? null,
    metadata:    { email, expires_hours, max_uses, invite_url: inviteUrl },
  });

  return NextResponse.json({
    invite_url:  inviteUrl,
    expires_at:  expiresAt,
    expires_hours,
    max_uses,
    email_sent:  !!process.env.RESEND_API_KEY,
  });
}
