import { NextResponse } from "next/server";
import { createSupabaseServerClient, createSupabaseAdminClient } from "@/lib/supabase-server";
import { logError } from "@/lib/log-error";

// POST /api/admin/portal-invite
// Body: { email, company_id, expires_hours?, max_uses? }
// Returns: { invite_url, expires_at, max_uses }
export async function POST(request: Request) {
  const origin = new URL(request.url).origin;

  // Verify caller is an admin
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthenticated" }, { status: 401 });

  const adminClient = createSupabaseAdminClient();
  const { data: profile } = await adminClient
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();

  if (profile?.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  // Parse body
  let body: { email?: string; company_id?: string; expires_hours?: number; max_uses?: number };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { email, company_id, expires_hours = 48, max_uses = 5 } = body;

  if (!email) return NextResponse.json({ error: "email is required" }, { status: 400 });

  const expiresAt = new Date(Date.now() + expires_hours * 60 * 60 * 1000).toISOString();

  // Create invite row (token auto-generated by DB default)
  const { data: invite, error: insertError } = await adminClient
    .from("portal_invites")
    .insert({
      email,
      company_id: company_id ?? null,
      expires_at: expiresAt,
      max_uses,
      created_by: user.id,
    })
    .select("token")
    .single();

  if (insertError || !invite) {
    await logError({
      error: insertError ?? new Error("No invite returned"),
      source: "api/admin/portal-invite",
      action: "insert_invite",
      userId: user.id,
      metadata: { email, company_id },
    });
    return NextResponse.json({ error: "Failed to create invite" }, { status: 500 });
  }

  const inviteUrl = `${origin}/portal/join/${invite.token}`;

  // Optionally send via Resend if RESEND_API_KEY is set
  if (process.env.RESEND_API_KEY) {
    try {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: "LexSutra <hello@send.lexsutra.com>",
          to:   [email],
          subject: "Your LexSutra portal access link",
          html: `
            <div style="font-family:sans-serif;max-width:480px;margin:0 auto;">
              <h2 style="color:#1a1a2e;">Your LexSutra portal access is ready</h2>
              <p>Click the button below to access your compliance portal.</p>
              <a href="${inviteUrl}"
                 style="display:inline-block;background:#c9a84c;color:#060a14;padding:12px 24px;
                        border-radius:6px;text-decoration:none;font-weight:600;margin:16px 0;">
                Access Portal →
              </a>
              <p style="color:#666;font-size:13px;">
                This link expires in ${expires_hours} hours and can be used up to ${max_uses} times.
                If you did not request this, please ignore this email.
              </p>
              <hr style="border:none;border-top:1px solid #eee;margin:24px 0;" />
              <p style="color:#999;font-size:12px;">
                LexSutra · EU AI Act Compliance · lexsutra.com
              </p>
            </div>
          `,
        }),
      });
    } catch (emailErr) {
      // Non-fatal — log but still return the invite URL
      await logError({
        error: emailErr,
        source: "api/admin/portal-invite",
        action: "send_email",
        userId: user.id,
        metadata: { email },
      });
    }
  }

  // Log to activity
  await adminClient.from("activity_log").insert({
    actor_id:    user.id,
    action:      "generate_portal_invite",
    entity_type: "companies",
    entity_id:   company_id ?? null,
    metadata:    { email, expires_hours, max_uses, invite_url: inviteUrl },
  });

  return NextResponse.json({
    invite_url:  inviteUrl,
    expires_at:  expiresAt,
    expires_hours,
    max_uses,
    email_sent:  !!process.env.RESEND_API_KEY,
  });
}
