"use client";

// Handles magic link sign-in for admin impersonation.
// Magic links generated by admin.generateLink() use the implicit flow —
// tokens arrive in the URL hash (#access_token=...) which is invisible to
// server-side routes. This client page picks up the session from the hash,
// checks the user's role, and redirects accordingly.

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

export default function MagicAuthPage() {
  const router  = useRouter();
  const [status, setStatus] = useState("Signing in…");

  useEffect(() => {
    const supabase = createSupabaseBrowserClient();

    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        if (event === "SIGNED_IN" && session) {
          subscription.unsubscribe();
          clearTimeout(timeout);

          const { data: profile } = await supabase
            .from("profiles")
            .select("role")
            .eq("id", session.user.id)
            .single();

          if (profile?.role === "client") {
            router.replace("/portal");
          } else if (profile?.role === "admin" || profile?.role === "reviewer") {
            router.replace("/admin");
          } else {
            setStatus("Not authorised — no profile found.");
            router.replace("/admin/login?error=not_authorized");
          }
        }
      }
    );

    // Fallback — if no SIGNED_IN event fires within 8s the link has expired or been used
    const timeout = setTimeout(() => {
      subscription.unsubscribe();
      setStatus("Link expired or already used.");
      router.replace("/admin/login?error=auth_failed");
    }, 8000);

    return () => {
      subscription.unsubscribe();
      clearTimeout(timeout);
    };
  }, [router]);

  return (
    <div
      style={{
        display:         "flex",
        alignItems:      "center",
        justifyContent:  "center",
        height:          "100vh",
        background:      "#080c14",
        flexDirection:   "column",
        gap:             "12px",
      }}
    >
      <div
        style={{
          width:        "24px",
          height:       "24px",
          border:       "2px solid rgba(45,156,219,0.3)",
          borderTop:    "2px solid #2d9cdb",
          borderRadius: "50%",
          animation:    "spin 0.8s linear infinite",
        }}
      />
      <p style={{ color: "#8899aa", fontSize: "14px" }}>{status}</p>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
