import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
  Svg,
  Path,
  Circle,
  Line,
} from "@react-pdf/renderer";
import React from "react";

// ── Types ──────────────────────────────────────────────────────────

export type ObligationItem = {
  number: string;
  name: string;
  article: string;
  status: string;
  finding: string;
  required_action: string;
  effort: string;
  deadline: string;
  confidence?: "low" | "medium" | "high";
  confidence_reason?: string;
  commercial_impact?: string;
};

export type StructuredReport = {
  risk_classification: string;
  risk_tier: string;
  annex_section: string;
  grade: string;
  executive_summary: string;
  obligations: ObligationItem[];
  // Richer fields generated by Claude — stored in DB, surfaced in PDF + admin UI
  identified_systems?: { name: string; description: string; likely_risk_tier: string }[];
  primary_system_assessed?: string;
  indicative_role?: "provider" | "deployer" | "provider_and_deployer" | "distributor";
  role_reasoning?: string;
  conformity_readiness?: "not_ready" | "early_stage" | "partially_structured" | "assessment_ready";
  conformity_readiness_note?: string;
  dsa_applicability?: "likely" | "possible" | "unlikely";
  dsa_note?: string;
  company_intelligence?: {
    employee_count?: string;
    founding_year?: string;
    funding_stage?: string;
    total_funding?: string;
    latest_round?: string;
    key_investors?: string[];
    headquarters?: string;
    industry?: string;
    signals?: string[];
  };
  pricing_recommendation?: {
    recommended_tier?: string;
    recommended_price?: string;
    confidence?: string;
    reasoning?: string;
    negotiation_note?: string;
  };
};

export type SnapshotPDFProps = {
  report: StructuredReport;
  companyName: string;
  reportRef: string;
  assessmentDate: string;
};

// ── Shield logo (SVG) ──────────────────────────────────────────────

function ShieldLogo({ size = 28 }: { size?: number }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 64 64">
      <Path
        d="M32 6 L56 15 L56 35 Q56 52 32 61 Q8 52 8 35 L8 15 Z"
        stroke="#c8a84b"
        strokeWidth={2.5}
        fill="rgba(200,168,75,0.10)"
        strokeLinejoin="round"
      />
      <Circle cx={32} cy={28} r={4} fill="#c8a84b" />
      <Circle cx={19} cy={21} r={2.5} fill="#2d9cdb" />
      <Circle cx={45} cy={21} r={2.5} fill="#2d9cdb" />
      <Circle cx={19} cy={37} r={2.5} fill="#2d9cdb" />
      <Circle cx={45} cy={37} r={2.5} fill="#2d9cdb" />
      <Circle cx={32} cy={46} r={2}   fill="#2d9cdb" opacity={0.65} />
      <Line x1={19} y1={21} x2={32} y2={28} stroke="#2d9cdb" strokeWidth={1.2} opacity={0.5} />
      <Line x1={45} y1={21} x2={32} y2={28} stroke="#2d9cdb" strokeWidth={1.2} opacity={0.5} />
      <Line x1={19} y1={37} x2={32} y2={28} stroke="#2d9cdb" strokeWidth={1.2} opacity={0.5} />
      <Line x1={45} y1={37} x2={32} y2={28} stroke="#2d9cdb" strokeWidth={1.2} opacity={0.5} />
      <Line x1={32} y1={46} x2={32} y2={32} stroke="#2d9cdb" strokeWidth={1.2} opacity={0.4} />
      <Line x1={19} y1={21} x2={45} y2={21} stroke="#2d9cdb" strokeWidth={0.8} opacity={0.28} />
      <Line x1={19} y1={37} x2={45} y2={37} stroke="#2d9cdb" strokeWidth={0.8} opacity={0.28} />
      <Line x1={19} y1={21} x2={19} y2={37} stroke="#2d9cdb" strokeWidth={0.8} opacity={0.28} />
      <Line x1={45} y1={21} x2={45} y2={37} stroke="#2d9cdb" strokeWidth={0.8} opacity={0.28} />
    </Svg>
  );
}

// ── Colour palette ─────────────────────────────────────────────────

const C = {
  blue:       "#1d6fa4",
  blueLight:  "#2d9cdb",
  dark:       "#0d1520",
  navyText:   "#8899aa",
  text:       "#1a2030",
  textMid:    "#4a5568",
  textLight:  "#6b7280",
  textGhost:  "#9ca3af",
  rule:       "#d1d5db",
  rowAlt:     "#f7f8fa",
  rowHeader:  "#e8ecf0",
  red:        "#c0392b",
  redBg:      "#fef2f2",
  redBorder:  "#f5c6c6",
  orange:      "#c05500",
  orangeBg:    "#fff4ed",
  orangeBorder:"#fbd5b5",
  amber:      "#b7770a",
  amberBg:    "#fffbeb",
  amberBorder:"#f5dfa0",
  green:      "#15803d",
  greenBg:    "#f0fdf4",
  greenBorder:"#bbf7d0",
  gold:       "#8b6914",
};

// ── Status helpers ─────────────────────────────────────────────────

function statusColor(s: string): string {
  if (s === "critical_gap")   return C.red;
  if (s === "not_started")    return C.orange;
  if (s === "partial")        return C.amber;
  if (s === "compliant")      return C.green;
  return C.textLight;
}

function statusBg(s: string): string {
  if (s === "critical_gap")   return C.redBg;
  if (s === "not_started")    return C.orangeBg;
  if (s === "partial")        return C.amberBg;
  if (s === "compliant")      return C.greenBg;
  return C.rowHeader;
}

function statusBorderColor(s: string): string {
  if (s === "critical_gap")   return C.redBorder;
  if (s === "not_started")    return C.orangeBorder;
  if (s === "partial")        return C.amberBorder;
  if (s === "compliant")      return C.greenBorder;
  return C.rule;
}

function statusLabel(s: string): string {
  if (s === "critical_gap")   return "CRITICAL GAP";
  if (s === "partial")        return "PARTIAL";
  if (s === "compliant")      return "COMPLIANT";
  if (s === "not_started")    return "NOT STARTED / NO EVIDENCE FOUND";
  if (s === "not_applicable") return "N/A";
  return s.toUpperCase().replace(/_/g, " ");
}

function statusLabelShort(s: string): string {
  if (s === "critical_gap")   return "CRITICAL GAP";
  if (s === "partial")        return "PARTIAL";
  if (s === "compliant")      return "COMPLIANT";
  if (s === "not_started")    return "NO EVIDENCE FOUND";
  if (s === "not_applicable") return "N/A";
  return s.toUpperCase().replace(/_/g, " ");
}

function priorityShort(s: string): string {
  if (s === "critical_gap")  return "P1";
  if (s === "not_started")   return "P2";
  if (s === "partial")       return "P3";
  if (s === "compliant")     return "P4";
  return "—";
}

function priorityLabel(s: string): string {
  if (s === "critical_gap") return "P1\nCRITICAL";
  if (s === "not_started")  return "P2\nNO EVIDENCE";
  if (s === "partial")      return "P3\nPARTIAL";
  if (s === "compliant")    return "P4\nCOMPLIANT";
  return "—";
}

function statusSortOrder(s: string): number {
  if (s === "critical_gap")  return 0;
  if (s === "not_started")   return 1;
  if (s === "partial")       return 2;
  if (s === "compliant")     return 3;
  return 4;
}

function abbreviateArticle(a: string): string {
  return a.split("|")[0].trim().replace("Article", "Art.").trim();
}

function confidenceColor(c?: string): string {
  if (c === "high")   return C.green;
  if (c === "medium") return C.amber;
  return C.textLight;
}

function confidenceLabel(c?: string): string {
  if (c === "high")   return "HIGH CONFIDENCE";
  if (c === "medium") return "MEDIUM CONFIDENCE";
  if (c === "low")    return "LOW CONFIDENCE";
  return "";
}

function formatRole(role?: string): string {
  if (role === "provider")              return "Provider — Article 3(3) EU AI Act";
  if (role === "deployer")              return "Deployer — Article 3(4) EU AI Act";
  if (role === "provider_and_deployer") return "Provider & Deployer";
  if (role === "distributor")           return "Distributor — Article 3(7) EU AI Act";
  return role ?? "—";
}

function formatConformityReadiness(r?: string): string {
  if (r === "not_ready")            return "Not Ready";
  if (r === "early_stage")          return "Early Stage";
  if (r === "partially_structured") return "Partially Structured";
  if (r === "assessment_ready")     return "Assessment Ready";
  return r ?? "—";
}

function conformityReadinessColor(r?: string): string {
  if (r === "assessment_ready")     return C.green;
  if (r === "partially_structured") return C.blue;
  if (r === "early_stage")          return C.amber;
  return C.red;
}

// ── Styles ─────────────────────────────────────────────────────────

const st = StyleSheet.create({
  // Page
  page:         { fontFamily: "Helvetica", fontSize: 8.5, color: C.text, backgroundColor: "#ffffff" },

  // Header bar
  hBar:         { backgroundColor: C.dark, flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 22, paddingVertical: 7 },
  hLogo:        { fontSize: 10, color: "#ffffff" },
  hLogoBold:    { fontFamily: "Helvetica-Bold", color: C.blueLight },
  hMeta:        { fontSize: 6.5, color: C.navyText, letterSpacing: 0.4 },

  // Footer bar
  fBar:         { backgroundColor: "#f2f4f6", borderTopWidth: 0.5, borderTopColor: C.rule, flexDirection: "row", justifyContent: "center", paddingVertical: 6 },
  fText:        { fontSize: 6.5, color: C.textGhost },

  // Watermark
  wm:           { position: "absolute", top: "40%", left: "10%", right: "10%", textAlign: "center", opacity: 0.04 },
  wmText:       { fontFamily: "Helvetica-Bold", fontSize: 64, color: C.dark },

  // Content padding
  body:         { paddingHorizontal: 36, paddingVertical: 22, flex: 1 },

  // Typography
  h1:           { fontFamily: "Times-Bold",    fontSize: 28, color: C.text,    lineHeight: 1.15, marginBottom: 3 },
  h2:           { fontFamily: "Times-Bold",    fontSize: 14, color: C.text,    borderBottomWidth: 1.5, borderBottomColor: C.blue, paddingBottom: 5, marginBottom: 12 },
  h3:           { fontFamily: "Helvetica-Bold",fontSize: 8.5, color: C.text   },
  subTitle:     { fontSize: 10, color: C.textMid, marginBottom: 14 },
  label:        { fontSize: 6.5, color: C.textGhost, letterSpacing: 0.6, textTransform: "uppercase", marginBottom: 3 },
  body1:        { fontSize: 8.5, color: C.text,     lineHeight: 1.65 },
  body2:        { fontSize: 8,   color: C.textMid,  lineHeight: 1.65 },
  small:        { fontSize: 7.5, color: C.textLight, lineHeight: 1.6  },

  // Grade badge (square)
  gradeBadge:   { width: 60, height: 60, borderRadius: 6, borderWidth: 1.5, borderColor: C.gold, backgroundColor: "#fdf8ee", alignItems: "center", justifyContent: "center" },
  gradeText:    { fontFamily: "Times-Bold", fontSize: 24, color: C.gold, lineHeight: 1 },

  // Metadata grid
  metaGrid:     { borderWidth: 0.5, borderColor: C.rule, borderRadius: 4, overflow: "hidden", marginTop: 14 },
  metaRow:      { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: C.rule },
  metaRowLast:  { flexDirection: "row" },
  metaLabel:    { width: 130, backgroundColor: C.rowHeader, paddingHorizontal: 10, paddingVertical: 6, fontFamily: "Helvetica-Bold", fontSize: 7.5, color: C.textMid },
  metaValue:    { flex: 1,   paddingHorizontal: 10, paddingVertical: 6, fontSize: 7.5, color: C.text },
  metaValueRed: { flex: 1,   paddingHorizontal: 10, paddingVertical: 6, fontSize: 7.5, color: C.red, fontFamily: "Helvetica-Bold" },

  // Risk callout box
  callout:      { borderLeftWidth: 3, borderLeftColor: C.gold, backgroundColor: "#fdf8ee", padding: 12, marginBottom: 10 },
  calloutTitle: { fontFamily: "Helvetica-Bold", fontSize: 8.5, color: C.text, marginBottom: 5 },

  // Table (summary + roadmap)
  table:        { borderWidth: 0.5, borderColor: C.rule, borderRadius: 4, overflow: "hidden", marginTop: 12 },
  tHead:        { flexDirection: "row", backgroundColor: C.rowHeader, paddingHorizontal: 8, paddingVertical: 6 },
  tHeadText:    { fontFamily: "Helvetica-Bold", fontSize: 7, color: C.textMid, textTransform: "uppercase", letterSpacing: 0.4 },
  tRow:         { flexDirection: "row", borderTopWidth: 0.5, borderTopColor: C.rule, paddingHorizontal: 8, paddingVertical: 6 },
  tRowAlt:      { flexDirection: "row", borderTopWidth: 0.5, borderTopColor: C.rule, paddingHorizontal: 8, paddingVertical: 6, backgroundColor: C.rowAlt },
  tCell:        { fontSize: 8, color: C.text, lineHeight: 1.5 },
  tCellGray:    { fontSize: 8, color: C.textLight, lineHeight: 1.5 },

  // Obligation card
  obCard:       { borderWidth: 0.5, borderColor: C.rule, borderRadius: 4, overflow: "hidden", marginBottom: 10 },
  obHeader:     { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 10, paddingVertical: 7, borderBottomWidth: 0.5, borderBottomColor: C.rule },
  obTitle:      { fontFamily: "Times-Bold", fontSize: 11, color: C.text },
  obRow:        { flexDirection: "row", borderTopWidth: 0.5, borderTopColor: C.rule },
  obRowLabel:   { width: 90, backgroundColor: "#f9fafb", paddingHorizontal: 8, paddingVertical: 7, fontFamily: "Helvetica-Bold", fontSize: 7.5, color: C.textLight, borderRightWidth: 0.5, borderRightColor: C.rule },
  obRowValue:   { flex: 1, paddingHorizontal: 10, paddingVertical: 7, fontSize: 8, color: C.text, lineHeight: 1.6 },
  obRowValueBlue: { flex: 1, paddingHorizontal: 10, paddingVertical: 7, fontSize: 8, color: C.blue, lineHeight: 1.6 },

  // Disclaimer
  disclaimer:   { borderWidth: 0.5, borderColor: C.rule, borderRadius: 4, padding: 10, marginTop: 12 },
  disclaimerTitle: { fontFamily: "Helvetica-Bold", fontSize: 7, color: C.textMid, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 4 },
  disclaimerText: { fontSize: 7, color: C.textLight, lineHeight: 1.65 },

  // Authenticity stamp
  stamp:        { borderWidth: 1, borderColor: C.gold, borderRadius: 4, padding: 12, marginTop: 12, backgroundColor: "#fdf8ee" },
  stampTitle:   { fontFamily: "Helvetica-Bold", fontSize: 8, textTransform: "uppercase", letterSpacing: 0.5, color: C.text, marginBottom: 6 },
  stampRow:     { flexDirection: "row", marginBottom: 3 },
  stampLabel:   { fontSize: 7.5, color: C.textMid, width: 160 },
  stampValue:   { fontSize: 7.5, fontFamily: "Helvetica-Bold", color: C.text, flex: 1 },

  // Roadmap priority
  prioCell:     { width: 62, paddingHorizontal: 6, paddingVertical: 6, alignItems: "center", justifyContent: "center", borderRightWidth: 0.5, borderRightColor: C.rule },
  prioText:     { fontFamily: "Helvetica-Bold", fontSize: 7, textAlign: "center", lineHeight: 1.3 },

  // Legend box (How to Read)
  legendBox:    { borderWidth: 0.5, borderColor: C.rule, borderRadius: 4, overflow: "hidden", marginBottom: 14 },
  legendHeader: { backgroundColor: C.dark, paddingHorizontal: 10, paddingVertical: 6 },
  legendHeaderText: { fontFamily: "Helvetica-Bold", fontSize: 8, color: "#ffffff", letterSpacing: 0.4 },
  legendRow:    { flexDirection: "row", borderTopWidth: 0.5, borderTopColor: C.rule, paddingHorizontal: 10, paddingVertical: 5, alignItems: "flex-start" },
  legendDot:    { width: 8, height: 8, borderRadius: 4, marginTop: 1, marginRight: 8, flexShrink: 0 },
  legendKey:    { width: 110, fontFamily: "Helvetica-Bold", fontSize: 7.5 },
  legendDesc:   { flex: 1, fontSize: 7.5, color: C.textMid, lineHeight: 1.5 },
});

// ── Reusable: Page header + footer ─────────────────────────────────

function PageHeader({
  reportRef,
  companyName,
}: {
  reportRef: string;
  companyName: string;
}) {
  return (
    <View style={st.hBar} fixed>
      <View style={{ flexDirection: "row", alignItems: "center", gap: 6 }}>
        <ShieldLogo size={16} />
        <Text style={st.hLogo}>
          <Text style={st.hLogoBold}>Lex</Text>Sutra
        </Text>
      </View>
      <Text style={st.hMeta}>
        CONFIDENTIAL  |  {reportRef}  |  {companyName}
      </Text>
    </View>
  );
}

function PageFooter({ assessmentDate }: { assessmentDate: string }) {
  return (
    <View style={st.fBar} fixed>
      <Text
        style={st.fText}
        render={({ pageNumber }) =>
          `Page ${pageNumber}  |  LexSutra EU AI Act Compliance Snapshot  |  ${assessmentDate}`
        }
      />
    </View>
  );
}

function Watermark() {
  return (
    <View style={st.wm} fixed>
      <Text style={st.wmText}>LEXSUTRA CONFIDENTIAL</Text>
    </View>
  );
}

// ── Cover page ─────────────────────────────────────────────────────

function CoverPage({
  report,
  companyName,
  reportRef,
  assessmentDate,
}: SnapshotPDFProps) {
  const criticalCount  = report.obligations.filter(o => o.status === "critical_gap").length;
  const nsCount        = report.obligations.filter(o => o.status === "not_started").length;
  const partialCount   = report.obligations.filter(o => o.status === "partial").length;
  const compliantCount = report.obligations.filter(o => o.status === "compliant").length;

  return (
    <Page size="A4" style={st.page}>
      <PageHeader reportRef={reportRef} companyName={companyName} />
      <Watermark />

      <View style={st.body}>
        {/* Wordmark + logo + rule */}
        <View style={{ flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 6 }}>
          <ShieldLogo size={42} />
          <View>
            <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 22, color: C.text, lineHeight: 1 }}>
              <Text style={{ color: C.blueLight }}>Lex</Text>Sutra
            </Text>
            <Text style={{ fontSize: 8, color: C.textLight, marginTop: 2 }}>EU AI Act Compliance Diagnostics</Text>
          </View>
        </View>
        <View style={{ height: 1.5, backgroundColor: C.blue, marginBottom: 8 }} />

        {/* Report type label */}
        <Text style={[st.label, { marginBottom: 6 }]}>EU AI Act Compliance Snapshot  ·  Public Footprint Assessment</Text>

        {/* Company name */}
        <Text style={st.h1}>{companyName}</Text>

        {/* Risk classification subtitle */}
        <Text style={[st.subTitle, { marginBottom: 16 }]}>
          {report.risk_classification}
        </Text>

        {/* Grade + stats row */}
        <View style={{ flexDirection: "row", alignItems: "flex-start", marginBottom: 16 }}>
          <View style={st.gradeBadge}>
            <Text style={st.gradeText}>{report.grade}</Text>
            <Text style={{ fontSize: 6, color: C.gold, marginTop: 1 }}>OVERALL GRADE</Text>
          </View>
          <View style={{ marginLeft: 14, justifyContent: "center", flex: 1 }}>
            <Text style={[st.small, { marginBottom: 5, color: C.textMid }]}>
              Assessment across 8 EU AI Act obligations — see page 2 for how grades and priorities are defined.
            </Text>
            {/* Explicit breakdown */}
            <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6 }}>
              {criticalCount > 0 && (
                <View style={{ backgroundColor: C.redBg, borderWidth: 0.5, borderColor: C.redBorder, borderRadius: 3, paddingHorizontal: 7, paddingVertical: 3 }}>
                  <Text style={{ fontSize: 7.5, fontFamily: "Helvetica-Bold", color: C.red }}>
                    {criticalCount} Critical Gap{criticalCount !== 1 ? "s" : ""}
                  </Text>
                </View>
              )}
              {nsCount > 0 && (
                <View style={{ backgroundColor: C.orangeBg, borderWidth: 0.5, borderColor: C.orangeBorder, borderRadius: 3, paddingHorizontal: 7, paddingVertical: 3 }}>
                  <Text style={{ fontSize: 7.5, fontFamily: "Helvetica-Bold", color: C.orange }}>
                    {nsCount} No Evidence Found
                  </Text>
                </View>
              )}
              {partialCount > 0 && (
                <View style={{ backgroundColor: C.amberBg, borderWidth: 0.5, borderColor: C.amberBorder, borderRadius: 3, paddingHorizontal: 7, paddingVertical: 3 }}>
                  <Text style={{ fontSize: 7.5, fontFamily: "Helvetica-Bold", color: C.amber }}>
                    {partialCount} Partial
                  </Text>
                </View>
              )}
              {compliantCount > 0 && (
                <View style={{ backgroundColor: C.greenBg, borderWidth: 0.5, borderColor: C.greenBorder, borderRadius: 3, paddingHorizontal: 7, paddingVertical: 3 }}>
                  <Text style={{ fontSize: 7.5, fontFamily: "Helvetica-Bold", color: C.green }}>
                    {compliantCount} Compliant
                  </Text>
                </View>
              )}
            </View>
          </View>
        </View>

        {/* Colour-coded obligation grid — instant scan */}
        <View style={{ borderWidth: 0.5, borderColor: C.rule, borderRadius: 4, overflow: "hidden", marginBottom: 14 }}>
          <View style={{ backgroundColor: C.dark, paddingHorizontal: 10, paddingVertical: 5 }}>
            <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 7, color: "#ffffff", letterSpacing: 0.4 }}>
              AT A GLANCE — ALL 8 OBLIGATIONS
            </Text>
          </View>
          {report.obligations.map((ob, i) => (
            <View
              key={ob.number}
              style={{
                flexDirection: "row",
                alignItems: "center",
                borderTopWidth: i === 0 ? 0 : 0.5,
                borderTopColor: C.rule,
                backgroundColor: statusBg(ob.status),
                paddingVertical: 5,
                paddingHorizontal: 0,
              }}
            >
              {/* Coloured left bar */}
              <View style={{ width: 4, alignSelf: "stretch", backgroundColor: statusColor(ob.status), marginRight: 10 }} />
              {/* Obligation name */}
              <Text style={{ fontSize: 7.5, color: C.text, flex: 1 }}>
                <Text style={{ fontFamily: "Helvetica-Bold" }}>{ob.number}</Text>{"  "}{ob.name}
              </Text>
              {/* Priority badge */}
              <Text style={{ fontSize: 7, fontFamily: "Helvetica-Bold", color: statusColor(ob.status), width: 22, textAlign: "center" }}>
                {priorityShort(ob.status)}
              </Text>
              {/* Status label */}
              <Text style={{ fontSize: 7, fontFamily: "Helvetica-Bold", color: statusColor(ob.status), width: 120, textAlign: "right", paddingRight: 10 }}>
                {statusLabelShort(ob.status)}
              </Text>
            </View>
          ))}
        </View>

        {/* Metadata grid */}
        <View style={st.metaGrid}>
          {([
            ["Assessment Date",    assessmentDate],
            ["Report Reference",   reportRef],
            ["Regulation",         "EU AI Act — Regulation (EU) 2024/1689"],
            ["Annex Reference",    report.annex_section || "Annex III"],
            report.indicative_role         ? ["Indicative Role",        formatRole(report.indicative_role)] : null,
            report.conformity_readiness    ? ["Conformity Readiness",   formatConformityReadiness(report.conformity_readiness)] : null,
            ["Assessment Basis",   "Public footprint scan only — internal documents not reviewed"],
            ["Reviewed By",        "LexSutra Expert Review"],
          ] as ([string, string] | null)[]).filter((r): r is [string, string] => r !== null)
            .map(([label, value], i, arr) => (
              <View key={i} style={i === arr.length - 1 ? st.metaRowLast : st.metaRow}>
                <Text style={st.metaLabel}>{label}</Text>
                <Text style={
                  label === "Conformity Readiness"
                    ? { ...st.metaValue, color: conformityReadinessColor(report.conformity_readiness), fontFamily: "Helvetica-Bold" }
                    : st.metaValue
                }>{value}</Text>
              </View>
            ))
          }
        </View>

        {/* Disclaimer */}
        <Text style={[st.small, { marginTop: 12, color: C.textGhost, lineHeight: 1.6 }]}>
          This report is produced by LexSutra as a compliance infrastructure tool and does not constitute legal advice.
          All findings are based on publicly available information only. Internal documentation may exist but was not reviewed.
        </Text>
      </View>

      <PageFooter assessmentDate={assessmentDate} />
    </Page>
  );
}

// ── How to Read This Report page ───────────────────────────────────

function HowToReadPage({
  reportRef,
  companyName,
  assessmentDate,
}: {
  reportRef: string;
  companyName: string;
  assessmentDate: string;
}) {
  return (
    <Page size="A4" style={st.page}>
      <PageHeader reportRef={reportRef} companyName={companyName} />
      <Watermark />

      <View style={st.body}>
        <Text style={st.h2}>How to Read This Report</Text>

        <Text style={[st.body2, { marginBottom: 14 }]}>
          This page explains the rating systems used throughout this report. All assessments are based
          exclusively on publicly available information — company website, published policies, press coverage,
          and public filings. Where no public evidence was found, this does not necessarily mean no compliance
          activity exists; internal documentation may be present but was not accessible for this snapshot.
        </Text>

        {/* Status legend */}
        <View style={[st.legendBox, { marginBottom: 14 }]}>
          <View style={st.legendHeader}>
            <Text style={st.legendHeaderText}>OBLIGATION STATUS — what each finding means</Text>
          </View>
          {[
            { color: C.red,       bg: C.redBg,   label: "CRITICAL GAP",               desc: "Public evidence indicates a significant compliance requirement is unmet. This poses direct legal risk under the EU AI Act. Immediate action is recommended." },
            { color: C.orange,    bg: C.orangeBg, label: "NOT STARTED / NO EVIDENCE FOUND", desc: "No public evidence of compliance activity was identified. Internal work may exist but is not publicly documented. Verification is recommended before the August 2026 deadline." },
            { color: C.amber,     bg: C.amberBg,  label: "PARTIAL",                     desc: "Some evidence of compliance exists, but the requirement is not fully met. Gaps remain that need to be addressed." },
            { color: C.green,     bg: C.greenBg, label: "COMPLIANT",                   desc: "Public evidence indicates the obligation is met. This finding reflects publicly available information and does not constitute a formal certification." },
          ].map((item, i) => (
            <View key={i} style={[st.legendRow, { backgroundColor: item.bg }]}>
              <View style={[st.legendDot, { backgroundColor: item.color }]} />
              <Text style={[st.legendKey, { color: item.color }]}>{item.label}</Text>
              <Text style={st.legendDesc}>{item.desc}</Text>
            </View>
          ))}
        </View>

        {/* Priority legend */}
        <View style={[st.legendBox, { marginBottom: 14 }]}>
          <View style={st.legendHeader}>
            <Text style={st.legendHeaderText}>PRIORITY LEVELS — remediation urgency in the roadmap</Text>
          </View>
          {[
            { color: C.red,   bg: C.redBg,   label: "P1 — Critical",    desc: "Confirmed compliance gap with direct legal risk. Action required immediately. These items are the highest legal exposure under the EU AI Act." },
            { color: C.orange, bg: C.orangeBg, label: "P2 — No Evidence", desc: "No public evidence found. Cannot confirm compliance. Must be verified or documented before the August 2026 deadline." },
            { color: C.amber,  bg: C.amberBg,  label: "P3 — Partial",     desc: "Partially compliant. Some work is in progress or documented, but gaps remain. Address before the deadline." },
            { color: C.green, bg: C.greenBg, label: "P4 — Compliant",   desc: "No action required based on current evidence. Monitor for regulatory updates and maintain existing documentation." },
          ].map((item, i) => (
            <View key={i} style={[st.legendRow, { backgroundColor: item.bg }]}>
              <View style={[st.legendDot, { backgroundColor: item.color }]} />
              <Text style={[st.legendKey, { color: item.color }]}>{item.label}</Text>
              <Text style={st.legendDesc}>{item.desc}</Text>
            </View>
          ))}
        </View>

        {/* Grade scale */}
        <View style={st.legendBox}>
          <View style={st.legendHeader}>
            <Text style={st.legendHeaderText}>OVERALL GRADE — composite score across all 8 obligations</Text>
          </View>
          <View style={[st.legendRow, { backgroundColor: C.rowAlt }]}>
            <Text style={[st.legendKey, { color: C.green, fontFamily: "Helvetica-Bold" }]}>A+ / A</Text>
            <Text style={st.legendDesc}>85–100% — Strong compliance posture. Most obligations met. Minor gaps only.</Text>
          </View>
          <View style={[st.legendRow]}>
            <Text style={[st.legendKey, { color: C.green, fontFamily: "Helvetica-Bold" }]}>B+ / B</Text>
            <Text style={st.legendDesc}>55–84% — Moderate compliance. Some obligations met, others partial. Action needed but risk is manageable.</Text>
          </View>
          <View style={[st.legendRow, { backgroundColor: C.rowAlt }]}>
            <Text style={[st.legendKey, { color: C.amber, fontFamily: "Helvetica-Bold" }]}>C+ / C</Text>
            <Text style={st.legendDesc}>25–54% — Significant gaps. Multiple obligations unaddressed. Compliance risk is elevated.</Text>
          </View>
          <View style={[st.legendRow]}>
            <Text style={[st.legendKey, { color: C.red, fontFamily: "Helvetica-Bold" }]}>D</Text>
            <Text style={st.legendDesc}>10–24% — Serious compliance deficit. Likely multiple critical gaps. Immediate engagement with compliance support is advised.</Text>
          </View>
          <View style={[st.legendRow, { backgroundColor: C.rowAlt }]}>
            <Text style={[st.legendKey, { color: C.red, fontFamily: "Helvetica-Bold" }]}>F</Text>
            <Text style={st.legendDesc}>Below 10% — No meaningful evidence of compliance across obligations. Highest legal risk category.</Text>
          </View>
          <View style={[st.legendRow, { borderTopWidth: 0.5, borderTopColor: C.rule }]}>
            <Text style={[{ fontSize: 7, color: C.textLight, lineHeight: 1.5, paddingHorizontal: 10, paddingVertical: 5, flex: 1 }]}>
              Hard overrides apply: 2+ critical gaps cap the grade at C+. 3+ critical gaps or 3+ unverified obligations cap the grade at D.
              Human Oversight (Art. 14) as a critical gap caps the grade at C+ regardless of other scores.
            </Text>
          </View>
        </View>

        {/* Assessment basis note */}
        <View style={{ marginTop: 14, borderLeftWidth: 3, borderLeftColor: C.blueLight, backgroundColor: "#f0f7ff", padding: 10 }}>
          <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 7.5, color: C.blue, marginBottom: 4 }}>
            Important: Assessment Basis
          </Text>
          <Text style={{ fontSize: 7.5, color: C.textMid, lineHeight: 1.6 }}>
            This snapshot is based exclusively on publicly available information gathered at the time of assessment.
            It is a pre-diagnostic tool — not a formal audit or certification. A full LexSutra diagnostic includes
            direct client questionnaire responses, document review, and expert analysis across all 8 obligations.
            Findings marked "No Evidence Found" may reflect strong internal compliance that is simply not publicly documented.
          </Text>
        </View>
      </View>

      <PageFooter assessmentDate={assessmentDate} />
    </Page>
  );
}

// ── Executive summary page ─────────────────────────────────────────

function ExecutiveSummaryPage({
  report,
  companyName,
  reportRef,
  assessmentDate,
}: SnapshotPDFProps) {
  const paras = report.executive_summary.split(/\n\n+/);

  // Sort obligations by severity for the summary table
  const sortedObligations = [...report.obligations].sort(
    (a, b) => statusSortOrder(a.status) - statusSortOrder(b.status)
  );

  return (
    <Page size="A4" style={st.page}>
      <PageHeader reportRef={reportRef} companyName={companyName} />
      <Watermark />

      <View style={st.body}>
        <Text style={st.h2}>Executive Summary</Text>

        {/* Risk classification callout box */}
        <View style={st.callout}>
          <Text style={st.calloutTitle}>
            Risk Classification:{" "}
            {report.risk_tier === "high_risk" ? "HIGH-RISK AI SYSTEM" : report.risk_tier.replace(/_/g, " ").toUpperCase()}
          </Text>
          <Text style={st.body2}>{paras[0] ?? ""}</Text>
        </View>

        {/* Remaining paragraphs */}
        {paras.slice(1).map((p, i) => (
          <Text key={i} style={[st.body2, { marginBottom: 8 }]}>{p}</Text>
        ))}

        {/* Identified AI Systems */}
        {report.identified_systems && report.identified_systems.length > 0 && (
          <View style={{ borderWidth: 0.5, borderColor: C.rule, borderRadius: 4, overflow: "hidden", marginBottom: 10 }}>
            <View style={{ backgroundColor: C.dark, paddingHorizontal: 10, paddingVertical: 5 }}>
              <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 7, color: "#ffffff", letterSpacing: 0.4 }}>
                IDENTIFIED AI SYSTEMS — all systems identified from public information
              </Text>
            </View>
            {report.identified_systems.map((sys, i) => {
              const isPrimary  = sys.name === report.primary_system_assessed;
              const tierColor  = sys.likely_risk_tier === "high_risk" ? C.red : sys.likely_risk_tier === "limited_risk" ? C.amber : C.green;
              const tierLabel  = sys.likely_risk_tier === "high_risk" ? "HIGH-RISK" : sys.likely_risk_tier === "limited_risk" ? "LIMITED-RISK" : "MINIMAL-RISK";
              return (
                <View key={i} style={{ flexDirection: "row", alignItems: "flex-start", borderTopWidth: i === 0 ? 0 : 0.5, borderTopColor: C.rule, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: isPrimary ? "#f7f9fc" : "#ffffff" }}>
                  {isPrimary && (
                    <View style={{ backgroundColor: C.blue, borderRadius: 2, paddingHorizontal: 5, paddingVertical: 1.5, marginRight: 7, marginTop: 1.5, flexShrink: 0 }}>
                      <Text style={{ fontSize: 6, color: "#ffffff", fontFamily: "Helvetica-Bold", letterSpacing: 0.3 }}>PRIMARY</Text>
                    </View>
                  )}
                  {!isPrimary && <View style={{ width: 40, marginRight: 7 }} />}
                  <View style={{ flex: 1 }}>
                    <Text style={{ fontSize: 8, fontFamily: "Helvetica-Bold", color: C.text, marginBottom: 1 }}>{sys.name}</Text>
                    <Text style={{ fontSize: 7.5, color: C.textMid, lineHeight: 1.4 }}>{sys.description}</Text>
                  </View>
                  <Text style={{ fontSize: 7, fontFamily: "Helvetica-Bold", color: tierColor, marginLeft: 10, marginTop: 1.5, flexShrink: 0 }}>
                    {tierLabel}
                  </Text>
                </View>
              );
            })}
          </View>
        )}

        {/* Obligation summary table — sorted by severity, colour-coded rows */}
        <View style={st.table}>
          <View style={st.tHead}>
            <Text style={[st.tHeadText, { width: 28 }]}>Pri.</Text>
            <Text style={[st.tHeadText, { flex: 3 }]}>Obligation</Text>
            <Text style={[st.tHeadText, { flex: 2.5 }]}>Status</Text>
            <Text style={[st.tHeadText, { flex: 2 }]}>Article</Text>
          </View>
          {sortedObligations.map((ob) => {
            const color = statusColor(ob.status);
            const bg    = statusBg(ob.status);
            return (
              <View
                key={ob.number}
                style={{ flexDirection: "row", borderTopWidth: 0.5, borderTopColor: C.rule, backgroundColor: bg, paddingHorizontal: 0, paddingVertical: 0 }}
              >
                {/* Coloured left accent bar */}
                <View style={{ width: 3, backgroundColor: color, alignSelf: "stretch" }} />
                {/* Priority */}
                <Text style={[st.tCell, { width: 25, paddingLeft: 6, paddingVertical: 6, fontFamily: "Helvetica-Bold", color }]}>
                  {priorityShort(ob.status)}
                </Text>
                {/* Obligation name */}
                <Text style={[st.tCell, { flex: 3, paddingVertical: 6 }]}>
                  {ob.number}. {ob.name}
                </Text>
                {/* Status */}
                <Text style={[st.tCell, { flex: 2.5, paddingVertical: 6, fontFamily: "Helvetica-Bold", color }]}>
                  {statusLabelShort(ob.status)}
                </Text>
                {/* Article */}
                <Text style={[st.tCellGray, { flex: 2, paddingVertical: 6, paddingRight: 8 }]}>
                  {abbreviateArticle(ob.article)}
                </Text>
              </View>
            );
          })}
        </View>

        <Text style={[st.small, { marginTop: 8, color: C.textGhost }]}>
          Table sorted by severity. See page 2 for a full explanation of statuses, priorities, and the grade scale.
          Detailed findings for each obligation are on the following pages.
        </Text>
      </View>

      <PageFooter assessmentDate={assessmentDate} />
    </Page>
  );
}

// ── Obligation assessment pages ────────────────────────────────────

function ObligationAssessmentPage({
  obligations,
  companyName,
  reportRef,
  assessmentDate,
}: {
  obligations: ObligationItem[];
  companyName: string;
  reportRef: string;
  assessmentDate: string;
}) {
  return (
    <Page size="A4" style={st.page}>
      <PageHeader reportRef={reportRef} companyName={companyName} />
      <Watermark />

      <View style={st.body}>
        <Text style={st.h2}>Detailed Obligation Assessment</Text>

        {obligations.map((ob) => {
          const color     = statusColor(ob.status);
          const headerBg  = statusBg(ob.status);
          const borderCol = statusBorderColor(ob.status);
          return (
            <View key={ob.number} wrap={false} style={[st.obCard, { borderColor: borderCol }]}>
              {/* Obligation header — colour-coded by status */}
              <View style={[st.obHeader, { backgroundColor: headerBg, borderBottomColor: borderCol }]}>
                <View style={{ flexDirection: "row", alignItems: "center", flex: 1 }}>
                  {/* Status colour bar */}
                  <View style={{ width: 3, height: 16, backgroundColor: color, borderRadius: 2, marginRight: 8 }} />
                  <Text style={st.obTitle}>{ob.number} {ob.name}</Text>
                </View>
                <View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}>
                  <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 7, color, letterSpacing: 0.3 }}>
                    {priorityShort(ob.status)}
                  </Text>
                  <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 7.5, color, letterSpacing: 0.3 }}>
                    {statusLabel(ob.status)}
                  </Text>
                </View>
              </View>

              {/* Legal Basis */}
              <View style={st.obRow}>
                <Text style={st.obRowLabel}>Legal Basis</Text>
                <Text style={st.obRowValueBlue}>{ob.article}</Text>
              </View>

              {/* Finding */}
              <View style={st.obRow}>
                <Text style={st.obRowLabel}>Finding</Text>
                <Text style={st.obRowValue}>{ob.finding}</Text>
              </View>

              {/* Confidence */}
              {ob.confidence && (
                <View style={st.obRow}>
                  <Text style={st.obRowLabel}>Confidence</Text>
                  <Text style={st.obRowValue}>
                    <Text style={{ fontFamily: "Helvetica-Bold", color: confidenceColor(ob.confidence) }}>
                      {confidenceLabel(ob.confidence)}
                    </Text>
                    {ob.confidence_reason ? `  —  ${ob.confidence_reason}` : ""}
                  </Text>
                </View>
              )}

              {/* Required Action */}
              <View style={st.obRow}>
                <Text style={st.obRowLabel}>Required Action</Text>
                <Text style={st.obRowValue}>{ob.required_action}</Text>
              </View>

              {/* Commercial Impact */}
              {ob.commercial_impact && (
                <View style={st.obRow}>
                  <Text style={st.obRowLabel}>Commercial Impact</Text>
                  <Text style={[st.obRowValue, { color: C.red, fontFamily: "Helvetica-Oblique" }]}>
                    {ob.commercial_impact}
                  </Text>
                </View>
              )}

              {/* Effort + Target */}
              {(ob.effort || ob.deadline) && (
                <View style={st.obRow}>
                  <Text style={st.obRowLabel}>Effort</Text>
                  <Text style={st.obRowValue}>
                    {ob.effort || "—"}
                    {ob.deadline ? `  |  Target: ${ob.deadline}` : ""}
                  </Text>
                </View>
              )}
            </View>
          );
        })}
      </View>

      <PageFooter assessmentDate={assessmentDate} />
    </Page>
  );
}

// ── Remediation roadmap page ───────────────────────────────────────

function RoadmapPage({
  report,
  companyName,
  reportRef,
  assessmentDate,
}: SnapshotPDFProps) {
  const items = [...report.obligations]
    .filter(o => o.status !== "not_applicable")
    .sort((a, b) => statusSortOrder(a.status) - statusSortOrder(b.status));

  return (
    <Page size="A4" style={st.page}>
      <PageHeader reportRef={reportRef} companyName={companyName} />
      <Watermark />

      <View style={st.body}>
        <Text style={st.h2}>Prioritised Remediation Roadmap</Text>
        <Text style={[st.body2, { marginBottom: 10 }]}>
          Ordered by urgency. P1 Critical items carry direct legal risk and require immediate action.
          P2 items have no publicly available evidence of compliance and must be verified or documented
          before the August 2026 deadline. See page 2 for a full explanation of priority levels.
        </Text>

        {/* Table */}
        <View style={[st.table, { marginTop: 4 }]}>
          {/* Header */}
          <View style={st.tHead}>
            <Text style={[st.tHeadText, { width: 62 }]}>Priority</Text>
            <Text style={[st.tHeadText, { flex: 3, paddingLeft: 6 }]}>Action Required</Text>
            <Text style={[st.tHeadText, { flex: 2, paddingLeft: 6 }]}>Obligation</Text>
            <Text style={[st.tHeadText, { width: 58, paddingLeft: 6 }]}>Effort</Text>
            <Text style={[st.tHeadText, { width: 58, paddingLeft: 6 }]}>Target</Text>
          </View>

          {items.map((ob) => {
            const color = statusColor(ob.status);
            const bg    = statusBg(ob.status);
            const pLabel = priorityLabel(ob.status);
            return (
              <View key={ob.number} wrap={false} style={{ flexDirection: "row", borderTopWidth: 0.5, borderTopColor: C.rule, backgroundColor: bg, paddingHorizontal: 0, paddingVertical: 0 }}>
                {/* Coloured left bar */}
                <View style={{ width: 3, backgroundColor: color, alignSelf: "stretch" }} />
                {/* Priority cell */}
                <View style={[st.prioCell, { borderRightWidth: 0.5, borderRightColor: C.rule }]}>
                  {pLabel.split("\n").map((line, j) => (
                    <Text key={j} style={[st.prioText, { color }]}>{line}</Text>
                  ))}
                </View>
                {/* Action */}
                <Text style={[st.tCell, { flex: 3, paddingHorizontal: 8, paddingVertical: 6, lineHeight: 1.5 }]}>
                  {ob.required_action || "—"}
                </Text>
                {/* Obligation */}
                <View style={{ flex: 2, paddingHorizontal: 8, paddingVertical: 6 }}>
                  <Text style={[st.tCell, { fontFamily: "Helvetica-Bold" }]}>{ob.name}</Text>
                  <Text style={st.tCellGray}>{abbreviateArticle(ob.article)}</Text>
                </View>
                {/* Effort */}
                <Text style={[st.tCellGray, { width: 58, paddingHorizontal: 8, paddingVertical: 6 }]}>
                  {ob.effort || "—"}
                </Text>
                {/* Target */}
                <Text style={[st.tCellGray, { width: 58, paddingHorizontal: 8, paddingVertical: 6 }]}>
                  {ob.deadline || "—"}
                </Text>
              </View>
            );
          })}
        </View>
      </View>

      <PageFooter assessmentDate={assessmentDate} />
    </Page>
  );
}

// ── Methodology & Authenticity page ────────────────────────────────

function MethodologyPage({
  report: _report,
  companyName,
  reportRef,
  assessmentDate,
}: SnapshotPDFProps) {
  return (
    <Page size="A4" style={st.page}>
      <PageHeader reportRef={reportRef} companyName={companyName} />
      <Watermark />

      <View style={st.body}>
        <Text style={st.h2}>Methodology &amp; Authenticity</Text>

        <Text style={[st.body1, { marginBottom: 10 }]}>
          This diagnostic snapshot was conducted using LexSutra&apos;s structured assessment methodology,
          which maps each EU AI Act obligation systematically against evidence gathered from public
          information: automated public footprint scan of company website, Terms of Service, privacy
          policy, and public AI-related disclosures. This snapshot precedes the full diagnostic process.
        </Text>

        <Text style={[st.body1, { marginBottom: 14 }]}>
          <Text style={{ fontFamily: "Helvetica-Bold" }}>Human-in-the-Loop: </Text>
          Every LexSutra diagnostic report is reviewed and approved by a human expert before delivery.
          This is not merely a quality control measure — it reflects LexSutra&apos;s core philosophy that
          compliance assessments affecting businesses and their stakeholders require human judgement.
          We practise the same principles we help our clients implement under the EU AI Act.
        </Text>

        {/* Authenticity stamp */}
        <View style={st.stamp}>
          <Text style={st.stampTitle}>Authenticity &amp; Version Stamp</Text>
          {[
            ["Report Reference:",               reportRef],
            ["Assessment Date:",                assessmentDate],
            ["Policy Version Assessed Against:", "EU AI Act v1.0 — Regulation (EU) 2024/1689"],
            ["Policy Active From:",             "August 2024"],
            ["Assessment Basis:",               "Public footprint scan — pre-diagnostic snapshot"],
            ["Reviewed and Approved By:",       "LexSutra Expert Review Team"],
          ].map(([label, value], i) => (
            <View key={i} style={st.stampRow}>
              <Text style={st.stampLabel}>{label}</Text>
              <Text style={st.stampValue}>{value}</Text>
            </View>
          ))}
          <Text style={[st.small, { marginTop: 8, color: C.textLight, lineHeight: 1.6 }]}>
            This report is permanently stamped against the above policy version. Historical validity
            of this report can be verified against the LexSutra Policy Version Archive at any time.
            Report reference {reportRef} corresponds to EU AI Act v1.0 and is immutable.
          </Text>
        </View>

        {/* Disclaimer */}
        <View style={[st.disclaimer, { marginTop: 14 }]}>
          <Text style={st.disclaimerTitle}>Disclaimer</Text>
          <Text style={[st.disclaimerText, { marginBottom: 6 }]}>
            This report is produced by LexSutra B.V. as a compliance infrastructure and diagnostic tool.
            It does not constitute legal advice and LexSutra is not a law firm. The findings,
            classifications, and recommendations reflect LexSutra&apos;s methodology and regulatory
            interpretation current at the date of assessment.
          </Text>
          <Text style={[st.disclaimerText, { marginBottom: 6 }]}>
            The client — {companyName} — is solely responsible for their own regulatory compliance under
            the EU Artificial Intelligence Act and all other applicable regulations. This report should be
            reviewed alongside qualified legal counsel before taking compliance decisions.
            LexSutra&apos;s liability is limited to the fee paid for this diagnostic service.
          </Text>
          <Text style={st.disclaimerText}>
            Money-back guarantee: If the methodology applied in this report is demonstrated to not accurately
            reflect the EU AI Act requirements as published at the date of assessment, LexSutra will provide
            a full refund of the diagnostic fee.
          </Text>
        </View>

        {/* Footer branding */}
        <Text style={[st.small, { marginTop: 16, textAlign: "center", color: C.textGhost }]}>
          LexSutra  ·  AI Compliance Diagnostic Infrastructure  ·  lexsutra.com  ·  Netherlands
        </Text>
      </View>

      <PageFooter assessmentDate={assessmentDate} />
    </Page>
  );
}

// ── Main PDF document ──────────────────────────────────────────────

export function SnapshotPDF(props: SnapshotPDFProps) {
  const { report } = props;

  return (
    <Document
      title={`LexSutra Compliance Snapshot — ${props.companyName}`}
      author="LexSutra"
      subject="EU AI Act Compliance Snapshot Report"
      creator="LexSutra Diagnostic Platform"
      producer="LexSutra"
    >
      {/* Page 1 — Cover */}
      <CoverPage {...props} />

      {/* Page 2 — How to Read This Report */}
      <HowToReadPage
        reportRef={props.reportRef}
        companyName={props.companyName}
        assessmentDate={props.assessmentDate}
      />

      {/* Page 3 — Executive Summary */}
      <ExecutiveSummaryPage {...props} />

      {/* Obligation Assessment — all 8 on one flowing page, cards never split */}
      <ObligationAssessmentPage
        obligations={report.obligations}
        companyName={props.companyName}
        reportRef={props.reportRef}
        assessmentDate={props.assessmentDate}
      />

      {/* Roadmap page */}
      <RoadmapPage {...props} />

      {/* Methodology & Authenticity */}
      <MethodologyPage {...props} />
    </Document>
  );
}
